### ISSUE TITLE
Plugin doesnt work

### ISSUE THREAD

**Issue by Melmoth-the-Wanderer** [erlandranvinge/ReAttach#12]
Hello,

the plugin has stopped working in my VS 2015. Plugin is installed but the icon is missing.
It used to be grayed out so I've tried to reinstall the plugin and then it disappeared.
This also happens to my colleague who is using VS 2017.

Regards,
MP

**Comment by tarasverq** [comment]
I also have this issue.

**Comment by ssa3512** [comment]
I am having the same issue. Plugin shows as installed and active but the buttons are not there.

**Comment by erlandranvinge** [comment]
Hi guys. This has something to do with the actual distribution of the plugin, please try to actually download the vsix file from the site and install it "manually" instead of installing the extension from within Visual Studio.

**Comment by ssa3512** [comment]
@erlandranvinge I tried uninstalling the plugin from visual studio and running the vsix from visualstudiogallery.com and the behavior is the same.

**Comment by tarasverq** [comment]
@erlandranvinge Maybe we need to delete some cache data or something else before reinstall plugin?

**Comment by tarasverq** [comment]
@erlandranvinge I installed old version from my downloads folder, and now all ok.

@ssa3512, @Melmoth-the-Wanderer, you can download it from zip file in attach.
[Reattach.zip](https://github.com/erlandranvinge/ReAttach/files/846885/Reattach.zip)

New version size is 572 kb, but old version have only 72 kb. What is the difference?
![image](https://cloud.githubusercontent.com/assets/8226275/23984993/80646a40-0a2d-11e7-9298-1db82d61b5ae.png)

**Comment by Melmoth-the-Wanderer** [comment]
@erlandranvinge, installing manually doesn't help at all :(

@tarasverq thanks for this temp solution :)

**Comment by erlandranvinge** [comment]
Hi, the increased size is due to a new version of Newtonsoft.Json being shipped with this version of ReAttach. Regarding the manual step, one might need to reset Visual Studio, it seems like the version from the marketplace is still present even after an uninstall. devenv.exe /Setup followed by devenv.exe /ResetUserData followed by a manual install. Warning: This will remove all your installed extensions and reset VS to its original defaults.

**Comment by ssa3512** [comment]
Removing the manually installed new version and installing a previously downloaded version (the 72kb installer) fixed this for me.

**Comment by Melmoth-the-Wanderer** [comment]
@ssa3512 assuming you're installing outdated version (1.2) instead of new one (2.0), am I right?
Have you tried doing so with package downloaded from VS Marketplace? (https://marketplace.visualstudio.com/items?itemName=ErlandR.ReAttach)

**Comment by erlandranvinge** [comment]
The issues present here seems real hard to track down. All my logs are silent, fuselog, eventlog, trace, activitylog, etc. It simply just wont install if downloaded through the gallery. I'm betting a lot this has to do with a missing dependency and/or signing issues. If any of you guys are unable to install the extension when going through a manual install (i.e. downloading the vsix and double clicking on it), there will be log files in users/[user]/appdata/temp named VSIXInstaller_... If I could get my hands on such a file I might be able to track down this madness.

**Comment by codeowl1** [comment]
I uninstalled, then closed VS 2015 and then ran the 2.1 ReAttach.vsix and then viewed the log afterwards and it contained the following.  Basically it is saying that it found ReAttach already installed in VS2015 even though I had uninstalled it and closed VS prior to running the vsix:

18/03/2017 7:00:05 PM - Microsoft VSIX Installer
18/03/2017 7:00:05 PM - -------------------------------------------
18/03/2017 7:00:05 PM - Initializing Install...
18/03/2017 7:00:05 PM - Extension Details...
18/03/2017 7:00:05 PM - 	Identifier         : 0ee94538-22b7-40c8-a253-3fce8ad39b6f
18/03/2017 7:00:05 PM - 	Name               : ReAttach
18/03/2017 7:00:05 PM - 	Author             : Erland Ranvinge
18/03/2017 7:00:05 PM - 	Version            : 2.1
18/03/2017 7:00:05 PM - 	Description        : ReAttach gives you an easy way to ReAttaching your prior debug targets. ReAttach stores your attach history for you and provides toolbar, menu and keyboard shortcuts for easy access.
18/03/2017 7:00:05 PM - 	Locale             : en-US
18/03/2017 7:00:05 PM - 	MoreInfoURL        : https://marketplace.visualstudio.com/items?itemName=ErlandR.ReAttach
18/03/2017 7:00:05 PM - 	InstalledByMSI     : False
18/03/2017 7:00:05 PM - 	SupportedFrameworkVersionRange : [4.5,)
18/03/2017 7:00:05 PM - 
18/03/2017 7:00:05 PM - 	SignatureState     : Unsigned
18/03/2017 7:00:05 PM - 	Supported Products : 
18/03/2017 7:00:05 PM - 		Microsoft.VisualStudio.Community
18/03/2017 7:00:05 PM - 			Version : [11.0,16.0]
18/03/2017 7:00:05 PM - 		Microsoft.VisualStudio.Pro
18/03/2017 7:00:05 PM - 			Version : [11.0,16.0]
18/03/2017 7:00:05 PM - 
18/03/2017 7:00:05 PM - 	References         : 
18/03/2017 7:00:05 PM - Signature Details...
18/03/2017 7:00:05 PM - 	Extension is not signed.
18/03/2017 7:00:05 PM - 
18/03/2017 7:00:05 PM - Searching for applicable products...
18/03/2017 7:00:05 PM - Found installed product - Microsoft Visual Studio Professional 2012
18/03/2017 7:00:06 PM - The extension with ID '0ee94538-22b7-40c8-a253-3fce8ad39b6f' is not installed to Microsoft Visual Studio Professional 2012.
18/03/2017 7:00:06 PM - Found installed product - Microsoft Visual Studio 2012 Shell (Integrated)
18/03/2017 7:00:06 PM - Found installed product - Microsoft Visual Studio Community 2015
18/03/2017 7:00:10 PM - An extension with a matching Identifier is already installed to this product.
18/03/2017 7:00:10 PM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
18/03/2017 7:00:10 PM - Found installed product - Global Location
18/03/2017 7:00:10 PM - Found installed product - AtmelStudio
18/03/2017 7:00:14 PM - The following target products have been selected...
18/03/2017 7:00:14 PM - 	Microsoft Visual Studio Professional 2012
18/03/2017 7:00:14 PM - 
18/03/2017 7:00:14 PM - Beginning to install extension to Microsoft Visual Studio Professional 2012...
18/03/2017 7:00:14 PM - Install to Microsoft Visual Studio Professional 2012 completed successfully. The extension has been installed to C:\USERS\USERNAME\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\11.0\EXTENSIONS\PMD0X2QK.BHD\

**Comment by codeowl1** [comment]
Also, not sure if this is related by I found this in the Windows 10 Event Viewer around the same time as I was removing and re-adding 2.1 and restarting VS, all just using the VS Extension Manager before downloading and running the vsix and trying a stand alone install.  I assume is happned when VS attempted to start 2.1:

Activation context generation failed for "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\redist\1033\vcredist_arm.exe". Dependent Assembly Microsoft.Windows.Common-Controls,language="&#x2a;",processorArchitecture="arm",publicKeyToken="6595b64144ccf1df",type="win32",version="6.0.0.0" could not be found. Please use sxstrace.exe for detailed diagnosis.

**Comment by codeowl1** [comment]
Also, I find that if I go into VS 2015 (I am running Update 3, which I just installed today, and could be the cause of the issue), and open the Extension Manager and Uninstall ReAttach, and then close and close VS.  Then open VS again, and open the Extension Manager, it is magically be in the list again, but is disabled.  So it doesn't seem to be uninstalling, and it seems to be related to VS 2015 Update 3, as I had no problem before this.

**Comment by codeowl1** [comment]
A further update.  I was able to uninstall using the command line:
vsixinstaller /u:0ee94538-22b7-40c8-a253-3fce8ad39b6f

And then when I installed using the 2.1 vsix it showed that it installed into both 2012 and 2015, and now it is not disabled when open VS 2015 and look in the Extension Manager.  However the ReAttach icon no long shows in the toolbar or the Debug Menu, so it is unusable.

Also this same behavior is happening in VS 2012 as well.  So maybe it is not to do with Update 3 of VS 2015.  I will next try uninstall and rolling back to previous version.

**Comment by codeowl1** [comment]
Rolling back to the zip provided by @tarasverq and then turning off automatic updates has worked.
@erlandranvinge, let me know if there is anything I can do to help you fix this great product ;-)

**Comment by erlandranvinge** [comment]
Hey @codeowl1, thanks for the assistance. Regardless of version of VS pre 2017 this problem will occur. When installing from the store, the plugin will be "half installed", e.g. it will be present in the plugin views but will not be activated. When trying to uninstall such an install, the plugin will be removed from the UI but the actual extension folder and its registration within VS will still be there. This is likely the cause behind several users in here not being able to install using the VSIX file after they tried the store. In order to get this to work you either have to remove the plugin manually (removing the folder and running devenv /setup or similar), or use vsixinstaller like you did. I'll look into the SideBySide exception you posted, likely it is not connected due to the fact that it specifies problems related to ARM.

**Comment by erlandranvinge** [comment]
A bit of an update here. There was nothing wrong with the ReAttach extension, the problems that is occurring is related to the actual distribution within the store. I've managed to reuse the same package under a different gallery item and everything magically works flawlessly. However, I would very much like to keep my stats/downloads etc, thus I'm still trying to get the version to actual get properly distribution under the original gallery item.

**Comment by erlandranvinge** [comment]
Now the issues seemed to have been resolved. Please try installing v2.2 of ReAttach. It should work regardless if you're using VS2012, VS2015 or VS2017. If you're having trouble uninstalling the old ReAttach, please use the command provided by @codeowl1: vsixinstaller /u:0ee94538-22b7-40c8-a253-3fce8ad39b6f
