### ISSUE TITLE
No support for Remote (no authentication) Transport

### ISSUE THREAD

**Issue by chrisglein** [erlandranvinge/ReAttach#13]
I attach to a process on my VM using the Attach to Process dialog and select "Remote (no authentication)" as the Transport. This works, all is well. Then in my ReAttach history it shoes the right process and IP address. Except when I click that I get the following dialog:

---------------------------
Microsoft Visual Studio
---------------------------
Connection request was rejected by the remote debugger. Ensure that the remote debugger is running in 'Windows Authentication' mode.
---------------------------
OK   
---------------------------

I would like to attach in the way that I did originally, _not_ with "Windows Authentication" as the Transport.

**Comment by erlandranvinge** [comment]
Hi, this is a known issue and the remote debugging support is still somewhat experimental. It's been on the list of "future stuff" for quite some time now:

https://github.com/erlandranvinge/ReAttach/blob/master/ReAttach/ReleaseNotes.txt

I wish I could give you a better answer, but it will get done when I get around to doing unless someone posts a pull request. It shouldn't be super complicated to get right, but is a pain to test with VM:s and clients running left and right and what not.
