### ISSUE TITLE
Startup performance in Visual Studio 2017

### ISSUE THREAD

**Issue by SylwesterZarebski** [erlandranvinge/ReAttach#17]
Hi,

  Visual Studio 2017 reports after startup:
![obraz](https://user-images.githubusercontent.com/1755531/33473449-caa99844-d676-11e7-8f98-fcaca53ae02b.png)
and in performance manager:
![obraz](https://user-images.githubusercontent.com/1755531/33473485-e81dce4a-d676-11e7-85a9-d658a08914ac.png)

Is there something i can do to remove this delay or better diagnose problem?

**Comment by gyphie** [comment]
I am also seeing this issue.   It is odd because when I first installed ReAttach I did not get the warning but recently it shows every time I start an instance of VS 2017.

**Comment by erlandranvinge** [comment]
Fix when asyncifying package.

**Comment by SylwesterZarebski** [comment]
Thanks a lot :-)
