### ISSUE TITLE
Add support for Visual Studio 2019

### ISSUE THREAD

**Issue by cb-eli** [erlandranvinge/ReAttach#20]
Visual Studio 2019 is out soon, please add support.

**Comment by cb-eli** [comment]
I see that support for visual studio 2019 was already added in Dec 2018. Can you update visual studio marketplace as well?

**Comment by D4rkiii** [comment]
Release is out *whoop whoop*
https://marketplace.visualstudio.com/items?itemName=ErlandR.ReAttach
