### ISSUE TITLE
VS 2022 support

### ISSUE THREAD

**Issue by Pirulax** [erlandranvinge/ReAttach#25]
It's pretty trivial.
I did it for myself on [my fork](https://github.com/Pirulax/ReAttach/tree/vs2022).

**Comment by Pirulax** [comment]
Okay, I got it to work.
I'll leave it here, just in case anyone wants it.

<details>
<summary>
Build from source
</summary>
I've also pushed the source to [my fork,](https://github.com/Pirulax/ReAttach/tree/vs2022) in case anyone wants to build it from source.
If you encounter any problems, try updating the VisualStudioSDK NuGet package. ([Source](https://github.com/dotnet/sdk/issues/12421#issuecomment-840506896))
To do this, go to `Manage NuGet Packages` -> `Browse` and type in `Microsoft.VSSDK.BuildTools`. Select the latest version (it should be selected by default), and click `update`.
</details>

[ReAttach.zip](https://github.com/erlandranvinge/ReAttach/files/7042230/ReAttach.zip)

**Comment by ten24bytes** [comment]
Thanks for this. You saved my time as I was gonna do this myself.

**Comment by AntonioKoB** [comment]
> Thanks for this. You saved my time as I was gonna do this myself. Although it would have been great if @erlandranvinge would have done this himself so that we can directly install it from the extensions store.

+1

**Comment by Pirulax** [comment]
Yall welcome guys.
Happy coding 😁

**Comment by mjl152** [comment]
@Pirulax, any chance you'd be willing to create a new VS extension pointing to your updated version? If @erlandranvinge is no longer responding it'd be good if someone can pick up the slack here. Otherwise, if you're willing I'd consider creating the new VS extension myself and pointing it towards your forked version. I'd love to have a more "official" install approach that I can point my colleagues to.

**Comment by ten24bytes** [comment]
That's some major rewrite! Thanks @erlandranvinge <3

**Comment by mjl152** [comment]
Fantastic news! Thanks @erlandranvinge !

**Comment by Pirulax** [comment]
> @Pirulax, any chance you'd be willing to create a new VS extension pointing to your updated version? If @erlandranvinge is no longer responding it'd be good if someone can pick up the slack here. Otherwise, if you're willing I'd consider creating the new VS extension myself and pointing it towards your forked version. I'd love to have a more "official" install approach that I can point my colleagues to.

Sorry for the late reply.
I have no previous experience with VS extensions I just needed it, and managed to get it work somehow, so yeah. But now it's officially out, so it's good.

@erlandranvinge 
Thank you for the great work! It's really useful!

Edit:
~~Seems like on the VS marketplace the description doesn't reflect the change? (It still doesn't say it supports vs2022 in the compatibility table)~~
Never mind, my bad
