### ISSUE TITLE
ReAttach to remote process, with No Authentication

### ISSUE THREAD

**Issue by semuel** [erlandranvinge/ReAttach#5]
I have a remote debugger configured as No Authentication.
I can Attach to this process, but when trying to ReAttach, it says that the remote debugger should be in Windows Authentication mode.

Thanks.

**Comment by erlandranvinge** [comment]
Hi there. 

Unfortunately, remote debugging without authentication is listed (see ReAttach/readme.txt on github) as a known issue and is not working. Hopefully, I'll find the time to correct this before the next version is pushed out. The current remote debugging feature is somewhat of an experiment and if I remember correctly, anonymous debugging required a fair amount of code to be written in order for it to blend in seamlessly with the UI etc. Feel free to contribute here.

Regards,
Erland

**Comment by semuel** [comment]
oh. thanks for building ReAttach!
