### ISSUE TITLE
Attachment exclusions

### ISSUE THREAD

**Issue by laingsimon** [erlandranvinge/ReAttach#6]
This tool is great, but a very useful addition would be to ignore certain processes from the attach history.

An example would be when debugging unit tests, if Resharper (or MsTest?) creates the process, then there is no ability to re-attach to it - it requires the test-harness to attach to the process.

I'm not sure how this could be integrated into the tool - maintaining the current minimalistic view; some options could be:
- Add an 'Ignore' button to the attach dialog
- Add a dialog/page to the Visual Studio Settings dialog

**Comment by erlandranvinge** [comment]
Thanks, this has been added to the list of upcoming features.
