### ISSUE TITLE
Feature Request: 'Automatically' Reattach to a process on launch? 

### ISSUE THREAD

**Issue by piyushsoni** [erlandranvinge/ReAttach#7]
Thanks for this great extension! Something even more awesome would be if I could automatically attach to the process when it is started (from some other process, for example). So if my executable is xyz.exe, as soon as it is started by anyone, Visual Studio attaches that automatically? (I'm just looking to attach to a child process of one I'm already debugging from Visual Studio). 

Thanks!

**Comment by erlandranvinge** [comment]
This might be implemented in the future, but with that said, it depends on if able to monitor process launches in a performant, non-intrusive way.
