### ISSUE TITLE
Remember the last debug code type

### ISSUE THREAD

**Issue by noscript** [erlandranvinge/ReAttach#8]
When debugging a WPF/C++ application ReAttach always tries to debug in Managed mode, basically ignoring the last selected mode in "Attach to Process" dialog. No way to re-attach in Native.

**Comment by erlandranvinge** [comment]
Yep, this is unfortunate, but the latest version on GitHub actually somewhat supports remembering debug engine. Try it out!

**Comment by erlandranvinge** [comment]
Since ReAttach 2.0, this is supported.
